[package]
name = "DNS_Server_Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
trust-dns-server = "0.23.2"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"