# UDP is implicit
server:
  #mode: Authoritative
  enable_tcp: false
  enable_https: false
  enable_tls: false
  basic_port: 53
  tls_port: 853
  https_port: 443
  ip_addrs: 
    - 10.0.5.1

#zones:
#  - namespace: nintendo.net.
#    zone_type: Primary
#    filepath: zones/nintendo.net.zone
#  - namespace: local.
#    zone_type: Primary
#    filepath: zones/local.zone

    