server:
  listen: # Listen sockets below preconfigured specifically for operating within a custom Linux access point 
    - address: 192.168.5.1
      port: 53
      protocol: udp

    - address: 192.168.5.1
      port: 53
      protocol: tcp

tcp:
  request_timeout_ms: 1000
  max_connections:
  idle_timeout_ms: 5000

logging:
  level: info
  query_log: true

recursion:
  enabled: true
  forwarders:
    - 8.8.8.8:53

zones:
  - name: nintendo.net.
    type: master
    file: zones/nintendo.net.zone
    dnssec:
      mode: disabled   # disabled | sign | validate
      keys:
        - key_path: keys/nintendo.net.zsk
          algorithm: RSASHA256
          role: zsk

  - name: local.
    type: master
    file: zones/local.zone
    dnssec:
      mode: disabled   # disabled | sign | validate

    